FROM pi-agent-python:latest

RUN apt update && \
    apt install -y build-essential

# ansible
RUN git clone https://github.com/TheShellLand/antsable /antsable && \
    cd /antsable && \
    bash install-ansible.sh && \
    # chrome, docker, sqlite3, sqlite-vec
    bash ansible-local.sh playbooks/readyup-agents.yml

COPY SKILLS /root/SKILLS

